// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, generateTile, printArray, randomCellIndices, randomInt;

  randomInt = function(x) {
    return Math.floor(Math.random() * x);
  };

  buildBoard = function() {
    return [0, 1, 2, 3].map(function() {
      return [0, 1, 2, 3].map(function() {
        return 0;
      });
    });
  };

  randomCellIndices = function() {
    return [randomInt(4), randomInt(4)];
  };

  generateTile = function() {
    var value;
    value = 2;
    console.log("randomInt: " + (randomInt(4)));
    return console.log("generate tile");
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("-- End --");
  };

  $(function() {
    var newBoard;
    newBoard = buildBoard();
    printArray(newBoard);
    generateTile();
    return generateTile();
  });

}).call(this);

//# sourceMappingURL=main.js.map
