// Generated by CoffeeScript 1.8.0
(function() {
  var buildBoard, generateTile, printArray;

  buildBoard = function() {
    var board, column, row, _i, _j;
    board = [];
    for (row = _i = 0; _i <= 3; row = ++_i) {
      board[row] = [];
      for (column = _j = 0; _j <= 3; column = ++_j) {
        board[row][column] = 0;
      }
    }
    console.log("build board");
    return board;
  };

  generateTile = function() {
    return console.log("generate tile");
  };

  printArray = function(array) {
    var row, _i, _len;
    console.log("-- Start --");
    for (_i = 0, _len = array.length; _i < _len; _i++) {
      row = array[_i];
      console.log(row);
    }
    return console.log("-- End --");
  };

  $(function() {
    var newBoard;
    newBoard = buildBoard();
    printArray(newBoard);
    generateTile();
    return generateTile();
  });

}).call(this);

//# sourceMappingURL=main.js.map
